"""Self-contained lite md2docx engine (bundled into the skill).

Barebones dependencies: markdown-it-py + python-docx only. No pydantic/typer.
This directory is generated by scripts/build_skills.py - do not edit by hand.
"""

from .core import ConvertResult, convert

__all__ = ["convert", "ConvertResult"]
