#!/usr/bin/env python3
"""Build/sync the self-contained skill bundles from the repo sources.

The skills under skills/ must not reference the rest of the repo, so the
engine code is *copied* into them. This is the single source of that copy — run
it whenever the engine, JS implementation, or branded theme changes (the
pre-commit hook does this automatically).

  python scripts/build_skills.py            # write the bundles
  python scripts/build_skills.py --check     # exit 1 if anything is out of date

Requires PyYAML (available in python/.venv); run via:
  uv --project python run python scripts/build_skills.py
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PY_SKILL = ROOT / "skills" / "md2docx-python"
JS_SKILL = ROOT / "skills" / "md2docx-js"

# (dirty flag accumulator for --check)
_CHANGES: list[str] = []


def _write(dest: Path, content: bytes, check: bool) -> None:
    existing = dest.read_bytes() if dest.exists() else None
    if existing == content:
        return
    _CHANGES.append(str(dest.relative_to(ROOT)))
    if not check:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(content)


def _copy(src: Path, dest: Path, check: bool, transform=None) -> None:
    data = src.read_bytes()
    if transform is not None:
        data = transform(data.decode("utf-8")).encode("utf-8")
    _write(dest, data, check)


# --- python skill: bundle the lite engine --------------------------------

_LITE_INIT = (
    '"""Self-contained lite md2docx engine (bundled into the skill).\n\n'
    "Barebones dependencies: markdown-it-py + python-docx only. No pydantic/typer.\n"
    "This directory is generated by scripts/build_skills.py - do not edit by hand.\n"
    '"""\n\n'
    "from .core import ConvertResult, convert\n\n"
    '__all__ = ["convert", "ConvertResult"]\n'
).encode("utf-8")


def _rewrite_imports(text: str) -> str:
    return (
        text.replace("from .config_models import", "from .config import")
        .replace("from ..config_models import", "from ..config import")
        .replace("md2docx.config_models", "md2docx_lite.config")
    )


def build_python(check: bool) -> None:
    src = ROOT / "python" / "src" / "md2docx"
    pkg = PY_SKILL / "md2docx_lite"

    _write(pkg / "__init__.py", _LITE_INIT, check)
    _copy(src / "core.py", pkg / "core.py", check, _rewrite_imports)
    _copy(src / "exceptions.py", pkg / "exceptions.py", check)
    _copy(src / "lite" / "config.py", pkg / "config.py", check, _rewrite_imports)
    for f in sorted((src / "render").glob("*.py")):
        _copy(f, pkg / "render" / f.name, check, _rewrite_imports)

    # branded theme (JSON, so the lite engine needs no pyyaml): derived from the
    # canonical YAML run-config, theme section only.
    import yaml

    y = yaml.safe_load((ROOT / "examples" / "02-branded" / "circeus-brand-light.yaml").read_text())
    brand = json.dumps({"theme": y["theme"]}, indent=2) + "\n"
    _write(PY_SKILL / "themes" / "circeus-brand.json", brand.encode("utf-8"), check)

    _copy(
        ROOT / "examples" / "02-branded" / "assets" / "circeus-logo-dark-charcoal.png",
        PY_SKILL / "assets" / "circeus-logo.png",
        check,
    )


# --- js skill: bundle the JS implementation ------------------------------

def build_js(check: bool) -> None:
    src = ROOT / "js"
    app = JS_SKILL / "app"

    for f in sorted((src / "src").glob("*.js")):
        _copy(f, app / "src" / f.name, check)
    _copy(src / "package.json", app / "package.json", check)
    _copy(src / "themes" / "circeus-light.json", app / "themes" / "circeus-light.json", check)
    _copy(
        ROOT / "examples" / "02-branded" / "circeus-brand-light.json",
        app / "themes" / "circeus-brand.json",
        check,
    )
    _copy(
        ROOT / "examples" / "02-branded" / "assets" / "circeus-logo-dark-charcoal.png",
        JS_SKILL / "assets" / "circeus-logo.png",
        check,
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="Report drift and exit 1 without writing.")
    args = ap.parse_args()

    build_python(args.check)
    build_js(args.check)

    if args.check:
        if _CHANGES:
            print("skill bundles are OUT OF DATE:", file=sys.stderr)
            for c in _CHANGES:
                print(f"  {c}", file=sys.stderr)
            print("run: uv --project python run python scripts/build_skills.py", file=sys.stderr)
            return 1
        print("skill bundles up to date.")
        return 0

    if _CHANGES:
        print(f"synced {len(_CHANGES)} file(s) into the skills:")
        for c in _CHANGES:
            print(f"  {c}")
    else:
        print("skill bundles already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
